# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: fc2c571
_src_path: git@github.com:MeteoSwiss-APN/mch-python-blueprint.git
email: capucine.lechartre@meteoswiss.ch
full_name: Capucine Lechartre
github_username: clechartre
module_name: BIOME4Py
project_doc_url: https://github.io/clechartre/BIOME4Py
project_github: https://github.com/clechartre/BIOME4Py
project_keywords: BIOME4Py
project_name: BIOME4Py
project_short_description: 'Hackathon project 2024: BIOME4Py'
project_slug: BIOME4Py
project_ssh_url: git+ssh://git@github.com/clechartre/BIOME4Py.git
python_version: '3.10'
version: 0.1.0
year: '2024'
