pipeline {
    options {
    // the variable $WORKSPACE is assigned dynamically at the beginning of every stage
    // and might change depending on the number of concurrent builds active.
    // We can only allow 1 concurrent build to have a consistent access to $WORKSPACE
    // Otherwise we should use stash/unstash for the miniconda installation
        disableConcurrentBuilds()
    }
    environment {
       PATH = "$WORKSPACE/miniconda/bin:$PATH"
    }
    agent {
        label 'tsa'
    }

    post {
        always{
            echo 'Cleaning up workspace'
            deleteDir()
        }
    }
    stages {
        stage('setup miniconda') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                bash tools/setup_miniconda.sh -p ${WORKSPACE}
                '''
            }
        }
        stage('build package') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source ${WORKSPACE}/miniconda/etc/profile.d/conda.sh
                conda init bash --no-user --install --system
                conda activate
                bash tools/setup_env.sh -n cloudai -u
                conda activate cloudai
                pip install --no-deps .
                '''
            }
        }
        stage('test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash --no-user --install --system
                conda activate cloudai
                pytest tests
                '''
            }
        }
        stage('dev-environment') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash --no-user --install --system
                conda activate
                bash tools/setup_env.sh -n dev-cloudai -u
                conda activate dev-cloudai
                pip install --no-deps --editable .
                '''
            }
        }
        stage('dev-test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash --no-user --install --system
                conda activate dev-cloudai
                pytest tests
                '''
            }
        }
        stage('pinned-environment') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash --no-user --install --system
                conda activate
                bash tools/setup_env.sh -n pinned-cloudai
                conda activate pinned-cloudai
                pip install --no-deps .
                '''
            }
        }
        stage('pinned-test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda activate pinned-cloudai
                pytest tests
                '''
            }
        }
        stage('pinned-dev-environment') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash --no-user --install --system
                conda activate
                bash tools/setup_env.sh -n pinned-dev-cloudai
                conda activate pinned-dev-cloudai
                pip install --no-deps --editable .
                '''
            }
        }
        stage('pinned-dev-test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda activate pinned-dev-cloudai
                pytest tests
                '''
            }
        }
    }
}
